# Generated by Django 4.2.7 on 2024-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpages', '0002_commentstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessWeeksTable',
            fields=[
                ('id_subgroup', models.IntegerField(primary_key=True, serialize=False)),
                ('id_week', models.IntegerField()),
            ],
            options={
                'db_table': 'access_weeks_table',
                'managed': False,
            },
        ),
    ]
